---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - syncthing
      - google-chrome 
      - macvim
      - atom
      - visual-studio-code
      - textmate
      - brave-browser
      - bitwarden
      - discord
      - obs
      - spotify
      - superduper
      - mos # Trackboll smooth scrolling
      - vlc
      - balenaetcher
      - iterm2
      - itsycal
      - grandperspective
      # - xrg
      - geektool
      - docker
      - visual-studio-code
    brew_packages:
      - syncthing
      - nano
      - nomad
      - wakeonlan
      - ipmitool
      - iperf3
      - nmap
      - cowsay
      - ffmpeg
      - git
      - handbrake
      - speedtest-cli
      - youtube-dl
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - neofetch
      - htop
      - docker-compose
      - docker-machine
    install_homebrew_if_missing: true
    # python_modules:
    #   - configparser
    #   - pylint
    #   - virtualenv
    upgrade_homebrew_packages: true

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: clone macos-dotfiles
      become_user: nick
      git:
        repo: https://github.com/crowsnesttech/macos-dotfiles.git
        dest: /Users/nick/git/dotfiles/macos-dotfiles
        clone: yes
        update: yes
        force: yes

    - name: clone oh-my-zsh
      become_user: nick
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh
        clone: yes
        update: yes
        force: yes

    - name: Symbolic link to oh-my-zsh
      file:
        src: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh
        dest: /Users/nick/.oh-my-zsh
        owner: nick
        group: staff
        state: link
        force: yes

    - name: Symbolic link to vimrc
      file:
        src: /Users/nick/git/dotfiles/macos-dotfiles/.vimrc
        dest: /Users/nick/.vimrc
        owner: nick
        group: staff
        state: link
        force: yes

    - name: Symbolic link to zshrc
      file:
        src: /Users/nick/git/dotfiles/macos-dotfiles/.zshrc
        dest: /Users/nick/.zshrc
        owner: nick
        group: staff
        state: link
        force: yes

    - name: Symbolic link to zshrc
      file:
        src: /Users/nick/git/dotfiles/macos-dotfiles/.nanorc
        dest: /Users/nick/.nanorc
        owner: nick
        group: staff
        state: link
        force: yes

    - name: clone zsh-autosuggestions
      become_user: nick
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes
        force: yes

    - name: Clone zsh-syntax-highlighting
      become_user: nick
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes
        force: yes

    - name: Copy custom ZSH theme
      copy:
        src: /Users/nick/git/dotfiles/macos-dotfiles/agnostercstm.zsh-theme
        dest: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh/custom/themes/
        remote_src: yes
        owner: nick
        group: staff
        mode: '755'
        
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Run iTerm Shell Int
      ansible.builtin.shell:
        cmd: cat /tmp/itermshellint.sh | sh -s -- -y

    # - name: Installing Python Modules
    #   pip:
    #     name: "{{ item }}"
    #     state: present
    #   with_items: '{{ python_modules }}'
    