- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Updating Homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
    when: ansible_machine == "x86_64"

  - name: clone macos-dotfiles
    become_user: nick
    git:
      repo: https://github.com/crowsnesttech/macos-dotfiles.git
      dest: /Users/nick/git/dotfiles/macos-dotfiles
      clone: yes
      update: yes
      force: yes

  - name: clone oh-my-zsh
    become_user: nick
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh
      clone: yes
      update: yes
      force: yes

  - name: Symbolic link to oh-my-zsh
    file:
      src: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh
      dest: /Users/nick/.oh-my-zsh
      owner: nick
      group: staff
      state: link
      force: yes

  - name: Symbolic link to vimrc
    file:
      src: /Users/nick/git/dotfiles/macos-dotfiles/.vimrc
      dest: /Users/nick/.vimrc
      owner: nick
      group: staff
      state: link
      force: yes

  - name: Symbolic link to zshrc
    file:
      src: /Users/nick/git/dotfiles/macos-dotfiles/.zshrc
      dest: /Users/nick/.zshrc
      owner: nick
      group: staff
      state: link
      force: yes

  - name: Symbolic link to zshrc
    file:
      src: /Users/nick/git/dotfiles/macos-dotfiles/.nanorc
      dest: /Users/nick/.nanorc
      owner: nick
      group: staff
      state: link
      force: yes

  - name: clone zsh-autosuggestions
    become_user: nick
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      clone: yes
      update: yes
      force: yes

  - name: Clone zsh-syntax-highlighting
    become_user: nick
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      clone: yes
      update: yes
      force: yes

  - name: Copy custom ZSH theme
    copy:
      src: /Users/nick/git/dotfiles/macos-dotfiles/agnostercstm.zsh-theme
      dest: /Users/nick/git/dotfiles/macos-dotfiles/.oh-my-zsh/custom/themes/
      remote_src: yes
      owner: nick
      group: staff
      mode: '755'

  - name: Tapping homebrew/cask-fonts
    homebrew_tap:
      name: homebrew/cask-fonts

  # - name: Change user Shell to ZSH 
  #   become: yes
  #   user:
  #     name: nick
  #     shell: /bin/zsh
  #   changed_when: false

  - name: Download iTerm Shell Integration Script
    ansible.builtin.get_url:
      url: https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh
      dest: /tmp/itermshellint.sh

  - name: Run iTerm Shell Int
    ansible.builtin.shell:
      cmd: cat /tmp/itermshellint.sh | sh -s -- -y

  - name: Updating Homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
    when: ansible_machine == "x86_64"

  - name: Installing Homebrew Cask Packages
    community.general.homebrew_cask:
      name: "{{ brew_cask_packages }}"
      state: present
      accept_external_apps: True
    when: ansible_machine == "x86_64"

  - name: Updating Homebrew M1 Pro
    homebrew:
      update_homebrew: yes
      upgrade_all: yes
    environment:
      PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    when: ansible_machine == "arm64"

  - name: Installing Homebrew Cask Packages M1 Pro
    community.general.homebrew_cask:
      name: "{{ brew_cask_packages }}"
      state: present
      accept_external_apps: True
    environment:
      PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    when: ansible_machine == "arm64"

  - name: Installing Homebrew Packages M1 Pro
    homebrew:
      name: "{{ brew_packages }}"
      state: present
    environment:
      PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    when: ansible_machine == "arm64"

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: nick
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/crowsnesttech/ansible_pull.git